name: TestPyPI
on:
  push:
    branches:
      - master
      - main
jobs:
  test_pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.8"
          architecture: x64
      - run: pip install --constraint=.github/workflows/constraints.txt poetry
      - run: >-
          poetry version patch &&
          version=$(poetry version | awk '{print $2}') &&
          poetry version $version.dev.$(date +%s)
      - run: poetry build
      - uses: pypa/gh-action-pypi-publish@v1.8.4
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
